Update README.md
aon3d/covid-face-shield pull request #12
Opened 2020-04-02 01:30 UTC by RocketUnicorn

Added printing instructions paragraph related to the M2 machine.

2020-04-02 03:32 UTC, mdtusz reviewed
Good additions - just some minor wording and voice changes. I'll let @nugvivi give the final review before full approval. 

:+1:

2020-04-02 03:32 UTC, mdtusz commented on README.md
> +Theses printing instruction are meant for printing on a AON-M2 or an AON-M2-2020.
```suggestion

The following instructions are intended for printing using the AON-M2 or an AON-M2-2020.
```

2020-04-02 03:32 UTC, mdtusz commented on README.md
> +1. Install a 0.6 mm nozzle heater block assembly. Instructions [here](https://docs.aon3d.com/maintenance/replace_hba/).
```suggestion

1. Install a 0.6 mm nozzle heater block assembly. Instructions [here](https://docs.aon3d.com/maintenance/replace_hba/). 
```

2020-04-02 03:32 UTC, mdtusz commented on README.md
> +2. Install the aluminum build plate. Ensure that the Kapton tape is in good condition on all the surfaces. (If not, follow [this procedure](https://docs.aon3d.com/maintenance/kapton_application/)to r
```suggestion
2. Install the aluminum build plate. Ensure that the Kapton tape is in good condition on all the surfaces. (If not, follow [this procedure](https://docs.aon3d.com/maintenance/kapton_application/) to replace it. 
```

2020-04-02 03:32 UTC, mdtusz commented on README.md
> +6. Once the chamber has reached thermal equilibrium, initiate the probing sequence on the entire bed  and set the Z offset. Instructions [here](https://docs.aon3d.com/calibration/z_calibration/).
```suggestion

6. Once the chamber has reached thermal equilibrium, initiate the probing sequence on the entire bed  and set the Z offset. Instructions [here](https://docs.aon3d.com/calibration/z_calibration/).
```

2020-04-02 03:32 UTC, mdtusz commented on README.md
> +We have included two generated G-codes that are ready to upload in your machine for you to start to print as soon as possible. They are intended to be used with ABS on a 0.6 mm nozzle. One of the G-c
```suggestion
We have included two generated G-code files that are ready for use on the AON-M2 and AON-M2-2020.
They are intended for use with ABS and a 0.6 mm nozzle.
One G-code file is specific for printing with T0 (left toolhead) and the other is for use with T1 (right toolhead).
```

2020-04-02 03:32 UTC, mdtusz commented on README.md
> +If you wish to modify the files, we also included the factory files to use with Simplify 3D. However, our settings have been tested and any modification can cause print defects.
```suggestion
If you wish to modify the files, the original factory files for use with Simplify 3D have been included.
However, the specified settings have been tested and any modification may cause print defects.
```

2020-04-02 03:32 UTC, mdtusz commented on README.md
> +Each print will get you 5 face shield frames.
```suggestion
Each print will yield 5 face shield frames. 
```

2020-04-02 03:32 UTC, mdtusz commented on README.md
> +- Place the parts in a sanitized bag for storage.
This section is a bit of a duplicate of what is written [here](https://github.com/aon3d/covid-face-shield/pull/12/files#diff-04c6e90faac2675aa89e2176d2eec7d8R73). Perhaps an edit or two to make it more specific, or migrate the handling procedures down here.

2020-04-02 13:44 UTC, engnadeau requested changes

2020-04-02 13:44 UTC, nnadeau commented on README.md
> +## Printing Instructions
```suggestion
## Printing Instructions

```

linebreak between heading and paragraph for markdown

2020-04-02 13:44 UTC, nnadeau commented on README.md
> +### Printer Preparation
```suggestion
### Printer Preparation

```

linebreak between heading and paragraph for markdown

2020-04-02 13:44 UTC, nnadeau commented on README.md
> +3. Clean the surface with IPA (isopropyl alcohol) 70% concentration minimum.
```suggestion
3. Clean the surface with IPA (isopropyl alcohol), minimum concentration of 70% for disinfection purposes.
```

2020-04-02 13:44 UTC, nnadeau commented on README.md
> +| Chamber    | 60°C        |
```suggestion
| Chamber    | 60°C        | 

```

2020-04-02 13:44 UTC, nnadeau commented on README.md
> +### Frame Removal
```suggestion
### Frame Removal

```

2020-04-03 00:20 UTC, RocketUnicorn commented on README.md
> +- Place the parts in a sanitized bag for storage.
done in : 0d407b5
https://github.com/aon3d/covid-face-shield/pull/12/commits/0d407b5170eecbc5f6190cfadee4c6f8afad5ad7

2020-04-03 00:21 UTC, RocketUnicorn reviewed
Thanks for your feedback! 
I integrated all your suggestions :)

2020-04-03 20:14 UTC, nugvivi commented on README.md
> +The following instructions are intended for printing using the AON-M2 or an AON-M2-2020.
```suggestion
The following instructions are intended for printing using the AON-M2 or AON-M2 2020.
```

2020-04-03 20:14 UTC, nugvivi commented on README.md
> +3. Clean the surface with IPA (isopropyl alcohol), minimum concentration of 70% for disinfection purposes.
Apply Dimafix or hairspray as well - ABS doesn't stick well enough to clean Kapton without brims. We don't want to use brims so we don't have to post-process

2020-04-03 20:14 UTC, nugvivi commented on README.md
> +| Extruder   | 250°C       |
Don't preheat the hot end yet

2020-04-03 20:14 UTC, nugvivi commented on README.md
> +6. Once the chamber has reached thermal equilibrium, initiate the probing sequence on the entire bed  and set the Z offset. Instructions [here](https://docs.aon3d.com/calibration/z_calibration/).
Use these probe bounds:
Left: 15
Right: 435
X Count: 10
Front: 15
Back/Rear: 435
Y Count: 10

2020-04-03 20:14 UTC, nugvivi commented on README.md
> +Plan 112g of ABS filament and 2 hours of print time per print.
```suggestion
Plan 112g of ABS filament and just over 2 hours of print time per print.
```

2020-04-03 20:14 UTC, nugvivi commented on README.md
> +How to remove the part from the build platform. Proceed following the aformentioned [handling(#handling) guidelines.
```suggestion
How to remove the part from the build platform. Proceed following the aformentioned [handling](#handling) guidelines. 
```
i think this needs the second square bracket?

2020-04-03 20:14 UTC, nugvivi commented on README.md
> +- Lower the bed and move the toolhead so you can access the parts easily. **The parts and machines might be hot!**
The gcode files and factory file should have a command in the ending script to move the tools to the back of the machine

2020-04-03 20:14 UTC, nugvivi commented on README.md
> +- Lower the bed and move the toolhead so you can access the parts easily. **The parts and machines might be hot!**
the bed and chamber temps are also left on at the end for quick restart

2020-04-08 18:58 UTC, RocketUnicorn commented on README.md
> +| Extruder   | 250°C       |
Removed the extruder line in the table

2020-04-08 19:01 UTC, RocketUnicorn commented on README.md
> +6. Once the chamber has reached thermal equilibrium, initiate the probing sequence on the entire bed  and set the Z offset. Instructions [here](https://docs.aon3d.com/calibration/z_calibration/).
Added a table with these values

2020-04-08 19:04 UTC, RocketUnicorn commented on README.md
> +- Lower the bed and move the toolhead so you can access the parts easily. **The parts and machines might be hot!**
Don't you think leave the chamber on, opening the door and removing the part will cause thermal runaway issues?

2020-04-08 19:06 UTC, RocketUnicorn commented on README.md
> +- Lower the bed and move the toolhead so you can access the parts easily. **The parts and machines might be hot!**
Anyway, I will raise an issue about this but for now I will include your instructions.

2020-04-08 19:08 UTC, RocketUnicorn commented on README.md
> +3. Clean the surface with IPA (isopropyl alcohol), minimum concentration of 70% for disinfection purposes.
Noted! It will be in the next version.

2020-04-09 14:14 UTC, engnadeau submitted a review, later dismissed

2020-04-10 20:07 UTC, nugvivi commented on README.md
> -- Touch points on printers (anywhere you might touch the machine) are wiped down regularly with IPA every 4h (e.g., twice a shift)
Why remove this?

2020-04-10 20:09 UTC, nugvivi requested changes
minor correction

2020-04-10 20:09 UTC, nugvivi commented on README.md
> -- Touch points on printers (anywhere you might touch the machine) are wiped down regularly with IPA every 4h (e.g., twice a shift)
Why remove this?

2020-04-10 20:09 UTC, nugvivi commented on README.md
> +- The toolheads, the build platform and the chamber will remain heated to allow for a quick restart.
```suggestion
- The build platform and the chamber will remain heated to allow for a quick restart.
```

2020-04-11 01:02 UTC, RocketUnicorn commented on README.md
> -- Touch points on printers (anywhere you might touch the machine) are wiped down regularly with IPA every 4h (e.g., twice a shift)
I did not recall removing this nor edited the ''handling'' section... What could have happened?

2020-04-11 01:04 UTC, RocketUnicorn commented on README.md
> -- Touch points on printers (anywhere you might touch the machine) are wiped down regularly with IPA every 4h (e.g., twice a shift)
@nnadeau any idea ?

2020-04-11 17:35 UTC, mdtusz commented on README.md
> -- Touch points on printers (anywhere you might touch the machine) are wiped down regularly with IPA every 4h (e.g., twice a shift)
It was Nic's commit here: https://github.com/aon3d/covid-face-shield/pull/12/commits/7848c8cfe22aca8b0f156060050f3739aff7385d 

You didn't do it!

2020-04-13 18:22 UTC, nugvivi approved these changes

2020-04-13 18:29 UTC, engnadeau approved these changes

2020-04-13 18:29 UTC, merged