Visor STEP + 1/8" CNC Mod + Revision # + date fix
aon3d/covid-face-shield pull request #19
Opened 2020-04-07 15:42 UTC by silvxm

- Uploaded Visor STEP
- Added DXF and STEP of shield mount for clearance to cut with 1/8" EM, easier for manufacture
- added revision numbers
- fixed date on visor drawing

2020-04-07 17:48 UTC, nnadeau commented
@silvxm please update the README to mention these new CNC files

2020-04-07 17:55 UTC, nnadeau commented
@silvxm i'm looking at the CNC DXF, how does the 1/8" EM fit in the inner corners?

2020-04-07 19:50 UTC, nnadeau commented
@silvxm i just added a `CHANGELOG.md` in a recent PR, can you please update your branch with respect to master and add these changes to the changelog

2020-04-07 20:28 UTC, silvxm commented
> @silvxm i'm looking at the CNC models, how does the 1/8" EM fit in the inner corners?

Sure does, MT concept milled it. Checked clearances beforehand

2020-04-07 20:53 UTC, silvxm commented
@nnadeau I edited changelog, readme. ready for review

2020-04-08 17:14 UTC, engnadeau requested changes

2020-04-08 17:14 UTC, nnadeau commented on CHANGELOG.md
> +## (20.04.01) - 2020-04-07
```suggestion
```

hasn't been "released" yet, so these changes are still under the unreleased section

2020-04-08 17:14 UTC, nnadeau commented on CHANGELOG.md
> +- COVID-001-Face-Shield-Frame_CNC_1_8-R01 .STEP and DXF for CNC milling w/ 1/8" cutter.
```suggestion
- `COVID-001-Face-Shield-Frame_CNC_1_8-R01` STEP and DXF for CNC milling w/ 1/8" cutter
```

2020-04-08 17:14 UTC, nnadeau commented on CHANGELOG.md
> +- Added Descriptor of CNC file addition to README.md
```suggestion
- Added descriptor of CNC file addition to `README.md`
```

2020-04-08 17:14 UTC, nnadeau commented on README.md
> +  - A second iteration of the frame is available and accommodates CNC milling with a 1/8" cutter.
```suggestion
  - A [second iteration of the frame](models/COVID-001-Face-Shield-Frame_CNC_1_8-R01.STEP) is available and accommodates CNC milling with a 1/8" cutter
```

2020-04-08 17:30 UTC, silvxm commented
@nnadeau changes committed!

2020-04-09 14:09 UTC, engnadeau approved these changes

2020-04-09 14:09 UTC, merged